### ISSUE TITLE
auto refresh failed

### ISSUE THREAD

**Issue by tjengbudi** [chaogei/Kiro-account-manager#7]
i try to autorefresh in the setting page, set to ON and sync account info to ON
however the usage token is not update at all. i check in the kiro IDE it already 150 and in the KAM still 99. the interval set to 10 minutes. i take 5 hour and still di not update at all.

**Comment by tjengbudi** [comment]
Account information about token used. It is not banned cause i still used
it in my kiro ide.

I did not aware about token cause i still use it in kiro ide

**Comment by chaogei** [comment]
The problem has been fixed.

**Comment by eryitunes-ux** [comment]
@chaogei looks like auto refresh failed. push button to refresh is ok and it works before. but if you set the auto refresh to on. change to 10 minutes interfal and sync info to ON. it will not refresh at a all. i see that the info never changed even with latest

**Comment by tjengbudi** [comment]
yes it is. mine also still doesn't work. push button works. but auto
refresh is not working

app version 1.3.1


for token i must wait 20-30 minutes. updates later
